# Generated by Django 6.1.1 on 2026-10-03 11:03
# Patched: removed swappable_dependency on AUTH_USER_MODEL and set db_constraint=False
# on all ForeignKeys referencing auth_user so the migration works on Supabase
# where auth tables do not exist (they live in the local SQLite auth_users.sqlite3).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Removed swappable_dependency to avoid cross-database FK constraint error.
        # The user table lives in a separate 'default' SQLite database.
        # db_constraint=False on the ForeignKey fields below handles this cleanly.
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('search_mode', models.CharField(default='keyword', help_text="Search engine utilized ('keyword' fallback or 'semantic' vector)", max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('component_type', models.CharField(choices=[('ALL', 'All Components'), ('CODE', 'Code'), ('DESIGN', 'Design')], default='ALL', help_text='Target component classification', max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='components.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. JWT Authentication Module', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what the component does and how to use it.')),
                ('component_type', models.CharField(choices=[('CODE', 'Code'), ('DESIGN', 'Design')], default='CODE', max_length=10)),
                ('keywords', models.CharField(help_text="Comma-separated keywords or tags, e.g. 'jwt, auth, token, security'", max_length=255)),
                ('author', models.CharField(default='Anonymous Developer', max_length=100)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='components/%Y/%m/')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('reuse_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Primary category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='components.category')),
                ('subcategory', models.ForeignKey(blank=True, help_text='Specific subcategory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_components', to='components.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('VIEW', 'View'), ('DOWNLOAD', 'Download'), ('REUSE', 'Reuse')], max_length=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='components.component')),
                # db_constraint=False: user lives in the default SQLite DB, not on Supabase
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReuseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reused_by', models.CharField(help_text='Developer or student name', max_length=150)),
                ('project_name', models.CharField(help_text='Target project or module', max_length=200)),
                ('action', models.CharField(default='Integrated into project', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Brief notes on how it was integrated')),
                ('reused_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuse_records', to='components.component')),
                # db_constraint=False: user lives in the default SQLite DB, not on Supabase
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reused_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=60)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_tags', to='components.component')),
            ],
            options={
                'unique_together': {('component', 'keyword')},
            },
        ),
    ]
