# Generated by Django 6.1.1 on 2026-10-06 20:00
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('components', '0002_alter_componentusage_user_alter_reuserecord_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=60)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='components.component')),
            ],
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='componentword',
            unique_together={('component', 'word')},
        ),
        migrations.AddIndex(
            model_name='componentword',
            index=models.Index(fields=['word'], name='components_componentword_word_idx'),
        ),
    ]
